### ISSUE TITLE
after phase block glitch

### ISSUE THREAD

**Issue by ewolkowicz** [kirbycope/one-block-bedrock#1]
Similar to the issues with the block transition between phase 7 and 8, the same glitch appears to happen after the countdown function runs.  The end portal gets added properly, but the block loops on the animation and counts up continuously as set here:
```
particle minecraft:water_evaporation_bucket_emitter 0.5 63.5 0.5
particle minecraft:explosion_particle 0.5 63 0.5
```
I tried digging through the code to see how you fixed it previously but I'm just too unfamiliar with minecraft to find it and the previous commits didn't seem to give me any clues.  If you can point me in the right direction I'm happy to add a PR for the fix!  Honestly this has been a fun learning experience knowing how bedrock functions work.  Oddly enough, if I run ```execute if score Phase phase matches 11 run function phase/after``` in game it sets a block and spawns a mob, but when you break the block, the looping issue happens.  Also, all functions are loaded in game so it might be something with the ```random/block/``` functions perhaps?

Piggy backing off this, what are your thoughts on adding deep dark blocks and/or ways to obtain things like armor trims?  Happy to collab on that if you want.

**Comment by kirbycope** [comment]
If you look at the [commit history](https://github.com/kirbycope/one-block-bedrock/commits) in git you'll find that all I did was fix the missing coordinates and block names. Those were causing a syntax error and the function could not be called. 
https://github.com/kirbycope/one-block-bedrock/commit/2b174b6c9930ed57e8b72666e9dca477f4d3be6b

**Comment by kirbycope** [comment]
https://github.com/kirbycope/one-block-bedrock/commit/897b70caf7d8d3f7ef56ee5e1e42b6fa3003a5d9

**Comment by kirbycope** [comment]
https://github.com/kirbycope/one-block-bedrock/commit/897b70caf7d8d3f7ef56ee5e1e42b6fa3003a5d9
